name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Do stuffs
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
          cd apps/client
          pnpm start
          pnpm test
