name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run end-to-end tests
        uses: cypress-io/github-action@v5
        with:
          build: pnpm build
          start: pnpm dev
